qemu.go
When downloading an image file with `source`, the progress is shown in the log.
=> show download progress

qemu.go, qemu_test.go
This imprement make enable to access internet from VMs.
---
how to verify
- cluster.yml
- seed.yml
- network.yml
https://gist.github.com/dulltz/f48416e62735c909ec17d6a6f524d0cf
```console
$ ./placemat cluster.yml
```
After a while qemu console window will be launched.
```console
cybozu@ubuntu $ ping 8.8.8.8
```
=> enable to access internet

qemu.go, server.go
Improve network shutdown.  Make destruction of the network resources on shutdown more gracefully.  The network will be destroyed when failure at starting VM, creating volume, and initializing networks.
=> Shutdown networks gracefully

README.md, cmd/placemat/yaml.go, cmd/placemat/yaml_test.go, examples/cluster.yaml, qemu.go, resource.go, server.go, server_test.go
* add `internal` property to Network resource
* add `use-nat` property to Network resource
=> Add support for internal switch and non-NAT bridge for Network resource.

SPEC.md, cmd/placemat/yaml.go, compress.go, resource.go
Currently, gzip and bzip2 are supported.
=> Add decompression support for Image resource.

cmd/placemat/main.go, yaml/yaml.go, yaml/yaml_test.go
because placemat-menu want to use placemat's YAML configuration
cybozu-go/placemat-menu#20
=> export yaml package

README.md, cmd/placemat/main.go, colored_log.go, qemu.go
placemat display logs aggregating stdout/stderr of multiple VMs and Pods.
It is impossible to distinguish the source of these logs.
So add prefix and colored logs.
=> support colored log

network.go
veth will be removed along with the network namespace
=> suppress error messages at exit

docs/pmctl.md, mtest/example_test.go, node_vm.go, pkg/pmctl/cmd/snapshot_list.go, server.go
- Also add error check of other snapshot subcommands.
=> Implement pmctl snapshot list

CHANGELOG.md, RELEASE.md
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
=> Bump version to 1.4.0

examples/README.md, examples/cluster.example.yml, examples/user-data.example.yml, mtest/example.go
Fixes: https://github.com/cybozu-go/placemat/issues/104
Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>
=> Fix examples.

bin/env
=> ci: move ci to asia-northeast2-c

bin/run-mtest.sh, cluster.go, docs/pmctl.md, docs/resource.md, mtest/Makefile, mtest/cluster.yml, mtest/env.go, mtest/suites.go, mtest/volume.go, node.go, node_volume.go
=> Expand support for node volume backend

CHANGELOG.md
=> Bump version to 1.5.0

CHANGELOG.md
=> Bump version to 1.5.1

node.go, node_test.go
Signed-off-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
=> Randomize MAC address for KVM

CHANGELOG.md
Signed-off-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
=> Bump version to 1.5.2

mtest/example.go, runtime.go
=> Activate vhost-net.

CHANGELOG.md
=> Bump version to 1.5.3

.gitignore, v1/Makefile
This PR removes mod vendor from v1 and tweaks v1 build.
=> Remove mod vendor from v1

docs/virtual_bmc.md, v2/go.mod, v2/pkg/virtualbmc/bmc_server.go, v2/pkg/virtualbmc/bmc_server_test.go, v2/pkg/virtualbmc/gencert.go, v2/pkg/virtualbmc/ipmi.go, v2/pkg/virtualbmc/ipmi_chassis.go, v2/pkg/virtualbmc/redfish.go, v2/pkg/virtualbmc/redfish_chassis.go, v2/pkg/virtualbmc/redfish_system.go
This PR implements Redfish server for Virtual BMC that supports
- ServiceRoot (redfish/v1)
- ComputerSystem (redfish/v1/Systems)
-  ComputerSystem.Reset 
- Chassis (redfish/v1Chassis)
- Chassis.Reset
=> Implement Redfish server

.github/workflows/ci.yaml, .github/workflows/release.yaml, README.md, RELEASE.md, bin/env, v2/Makefile, v2/debian/DEBIAN/control
This PR includes a release workflow definition file and document updates.
=> Prepare for release

CHANGELOG.md, README.md, docs/upgrade_v2.md, docs/virtual_bmc.md, v2/version.go
=> Bump version to 2.0.0

v2/e2e/cluster.yml, v2/e2e/placemat_test.go, v2/pkg/dcnet/netns.go
=> Fix goroutine captures loop variable

CHANGELOG.md
=> Bump version to 2.0.1

CHANGELOG.md, RELEASE.md, v2/version.go
=> Bump version to 2.0.2

.github/workflows/ci.yaml, v2/pkg/virtualbmc/suite_test.go
=> Stabilize small test by extending timeout period

CHANGELOG.md, v2/version.go
=> Bump version to 2.0.3

examples/README.md, examples/cluster.example.yml, examples/user-data.example.yml, v2/cmd/placemat2/sub/run.go
This PR fixes the example by using Flatcar. It also fixes the bug that doesn't expand SUDO_USER environment variable.
=> Fix example

CHANGELOG.md, v2/version.go
=> Bump version to 2.0.4

docs/pmctl.md
=> Update pmctl document

CHANGELOG.md, v2/version.go
=> Bump version to 2.0.5

v2/pkg/dcnet/netns.go, v2/pkg/dcnet/netns_test.go
=> Disable rp_filter inside a netns

CHANGELOG.md, v2/version.go
=> Bump version to 2.0.6

CHANGELOG.md, v2/version.go
issue: https://github.com/cybozu/csa/issues/62
Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>
=> Bump version to 2.1.0

docs/resource.md, v2/pkg/types/cluster.go, v2/pkg/types/cluster_test.go, v2/pkg/vm/node.go, v2/pkg/vm/qemu.go, v2/pkg/vm/qemu_test.go
part of https://github.com/cybozu-go/neco/issues/1977
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>
=> flexible SMP configuration for nodes

CHANGELOG.md, v2/version.go
=> Bump version to 2.2.0

CHANGELOG.md, v2/version.go
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>
=> Bump version to 2.3.0

CHANGELOG.md, v2/version.go
Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>
=> Bump version to 2.3.1

v2/pkg/vm/volume.go
Starting with QEMU v6.1, qemu-img now requires an explicit format specification to create or modify images that depend on backing_file.
https://github.com/qemu/qemu/blob/master/docs/about/removed-features.rst#qemu-img-backing-file-without-format-removed-in-61
Since qemu v6.2 is installed on Ubuntu 22.04, I change qemu-img to explicitly specify the format
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>
=> Explicit the image format

CHANGELOG.md, v2/version.go
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>
=> Bump version to 2.4.0

.github/workflows/ci.yaml
=> Rename env variable name for SA key

CHANGELOG.md, v2/version.go
Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>
=> Bump version to 2.4.1

CHANGELOG.md
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>
=> Bump version to 2.4.2

CHANGELOG.md, v2/version.go
Signed-off-by: YZ775 <yuzuki-mimura@cybozu.co.jp>
=> Bump version to 2.4.3

CHANGELOG.md, v2/version.go
=> Bump version to 2.4.5

CHANGELOG.md, v2/version.go
Signed-off-by: YZ775 <yuzuki-mimura@cybozu.co.jp>
=> Bump version to 2.4.6

CHANGELOG.md, v2/version.go
Signed-off-by: YZ775 <yuzuki-mimura@cybozu.co.jp>
=> Bump version to 2.4.7

CHANGELOG.md, v2/version.go
Signed-off-by: Maho Takara <takara@cybozu.co.jp>
=> Bump version to 2.4.8

CHANGELOG.md, v2/version.go
=> Bump version to 2.4.9
