cybozu-go/placemat

.gitignore, cmd/placemat/yaml.go, cmd/placemat/yaml_test.go, resource.go, server.go, server_test.go
This PR introduces **NodeSet** resouce.
The properties (spec) that can be defined in the NodeSet resource are as follows.
- `replicas`: number of nodes to create
- `template`: Specify a template to be applied to the spec of the Node resource.
NodeSet creates `spec.replicas` Nodes.
Each Node's name is `"${name}-$i"` (`i` is a serial number).
In the `spec.template`, describe the spec of the Node resource.
---
In the example below, nodes of `worker-1`, `worker-2`, `worker-3` are created.
```yaml
kind: NodeSet
name: worker
spec:
replicas: 3
template:
interfaces:
- my-net
volumes:
- name: data
size: 10GB
```
=> NodeSet resource

cmd/placemat/yaml.go, cmd/placemat/yaml_test.go, qemu.go, resource.go, server.go, server_test.go
Network resource is supported.  Define Network resources as following:
```yaml
kind: Network
name: net1
spec:
addresses:
- 172.16.0.1/24
---
kind: Node
name: boot-0
spec:
volumes:
- name: system
size: 10G
recreatePolicy: Never
interfaces:
- net1
```
Placemat creates bridges (virtual L2 bridges) corresponding to Network resources.  The `addresses` parameter contains IP addresses which host assigns to the bridge.
You can observe a bridge named `net1`, and TAP named `boot-0_net1` which VM connets.  The VM can connecto to host's bridge with IP addresses `172.16.0.0/24`.
```console
$ ip link
1126: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
link/ether ea:43:bc:a8:bf:51 brd ff:ff:ff:ff:ff:ff
1127: boot-0_net1: …
```
=> Network resource

cmd/placemat/yaml.go, cmd/placemat/yaml_test.go, qemu.go, resource.go
This PR adds two volume's fields `source` and `cloud-config`, and adds `resources` field.
One of `size`, `source` or `cloud-config` can be specified as the volume type.
* `size` : create an empty volume image using `qemu-img`
* `source`: use the image downloaded from the specified URL
* `cloud-config`: create  a volume image using `cloud-localds` with the specified config file
The `resources` field specifies the resource to be assigned to the VM.
* `cpu`: number of cpu cores
* `memory`: amount of memory
In the example below, the node has three type volumes, 4cpu and 8G memory.
```yaml
kind: Node
name: boot-1
spec:
volumes:
- name: data
size: 10G
- name: ubuntu
source: https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img
recreatePolicy: …
```
=> Create volume from url

cmd/placemat/main.go, cmd/placemat/yaml.go, cmd/placemat/yaml_test.go, qemu.go, qemu_test.go, resource.go
- To set IP address using Ubuntu cloud image, enable to set the `--network-config` option of `cloud-localds`.
- give a unique MAC address each NICs.
=> Enable to set ip addresses by ubuntu cloud image

cmd/placemat/yaml.go, cmd/placemat/yaml_test.go, qemu.go, resource.go
New property `bios` is available for a Node resource:
```yaml
kind: Node
name: boot-0
spec:
bios: uefi  # legacy or ueif
```
If `bios: legacy` is set or `bios` property is not set, QEMU launch a VM with legacy BIOS.  If `bios: ueif` is set, QEMU launch a VM with UEFI.  UEFI is loaded by OVMF, and data in NVRAM is persisted into the disk on the host machine.
=> Enable UEFI and persist NVRAM

cmd/placemat-connect/main.go
C-[ is used in escape cahracters. picocom failed to send escape keys to
serial console.  It has been changed to C-q.
=> Use C-q prefix for placemat-connect

README.md, cmd/placemat/yaml.go, cmd/placemat/yaml_test.go, qemu.go, qemu_test.go, resource.go
System Management BIOS (SMBIOS) properties are supported for a Node resource as the following:
```yaml
kind: Node
name: my-node
spec:
smbios:
manufacturer: cybozu
product: mk2
serial: 1234abcd
```
It can observe by a `dmidecode` command from Linux userspace:
```console
$ sudo dmidecode -s system-manufacturer
cybozu
$ sudo dmidecode -s system-product-name
mk2
$ sudo dmidecode -s system-serial-number
1234abcd
```
=> Support SMBIOS property for a Node resource

SPEC.md, cmd/placemat/yaml.go, qemu.go, resource.go
Using QEMU -fw_cfg with opt/com.coreos/config key,
Ignition file can be passed to the CoreOS image.
=> Add support for Ignition.

cmd/placemat/main.go
In YAML, file paths are often written as relative from the YAML
itself.  If placemat is invoked from the directory other than the
directory of YAML file, such files cannot be located.
To allow such relative paths in YAML, this commit let placemat
chdir to the directory of the first YAML given in command-line.
=> [placemat] chdir to the directory of YAML file

README.md, cmd/placemat/main.go, qemu.go
This commit adds a new command-line option "-cache-dir".
It specifies the directory for cached data.
In addition, -nographic option is replaced with -graphic
reversing the behavior.
=> Split cache directories from -data-dir to -cache-dir.

.circleci/config.yml
This commit replaces circleci/golang with our own quay.io/cybozu/golang.
=> Change Go container for CircleCI.

network.go, sysctl.go, sysctl_test.go
When placemat creates a NAT-enabled virtual network, it installs NAT rules to iptables.
In addition to iptables, however, the host operating system need to forward packaets
between interfaces to allow NATed connections from virtual machines.
This PR makes placemat automatically enable packet forwarding at the same time
when it installs NAT rules.  Packet forwarding is disabled when placemat exits if
they were not enabled.
=> Turn on IP forwarding when NAT is enabled

docs/resource.md, pod.go
Currently ip forwarding setting of Pod inherits the settings of the parent's NS,
but considering Pod's use case, it should be set to enable by default.
=> Enable IP forwarding in Pod namespaces

README.md, cluster.go, cmd/placemat/main.go, network.go, node.go, rootfs.go, runtime.go
- cause
異常終了したときは正規の終了動作が行われない。
- summary
placematを実行するときに **`-force`** 引数を追加し、この場合には終了動作を行ってから実行に移る。
`$ placemat -force cluster.yml`
- `ip tuntap delete ~ `, `ip link delete ~ ` よりip linkが削除される
- `iptables -X ~ ` よりiptableが削除される
- `/placemat-root/~` がunmountされる
- `/run/netns/~` がunmountされる
- `monitor`, `.socket`, `.guest` が削除される
- changes
- `main.go`, `runtime,go` に`-force` パラメータを追加するためのコードを追加
- `rootfs.go` に記述された、`/placemat-rootxxxxxxxxxxxx`のフォルダを`/placemat-root`に変更
- 異常終了時消去するためにディレクトリ名が一意のほうが実装しやすい
- そもそも複数存在しても以前のmountがある限り新しくmountできないため一意で良い
- `cluster.go` にCleanupメソッドを追加
- `destroyNatRules()`でiptablesの削除
- `os.Remove()`での通信用`monitor`, `.socket`, `.guest`ファイルの削除
- `deletePodNS()`でのnetnsの削除
- `nameGenerator`でネットワーク名を検索し`n.Destroy()`でネットワークの削除
- …
=> add cleanup func

cmd/placemat/main.go
`pkill placemat` command can not find child process.
=> change child process name to `placemat`

node_vm.go, server.go
In Neco, Boot servers resumes VM session earlier than Worker nodes.
It makes that system clocks are differ after loading snapshots.
To solve this problem, wait to run "cont" command after taking/loading
snapshots.
=> [snapshot] Synchronize resuming VMs

node.go
Ref: https://wiki.gentoo.org/wiki/QEMU/Options
=> Add qemu option to use para-virtualized RNG for fast boot

node.go
GCE instances can be stable using host CPU flags.
=> Use host CPU flags with (qemu -cpu host) for stability

mtest/cluster.yml, mtest/volume.go, node_volume.go
=> Fix aio option when volume cache parameter is specified

node_volume.go
Avoid warning message like below on qemu 2.11.1.
`Opening non-rw vvfat images without an explicit read-only=on option is deprecated. Future versions will refuse to open the image instead of automatically marking the image read-only.`
And in fact Qemu 4.2.1 has come to refuse, so this fix becomes necessary.
ref. https://wiki.qemu.org/ChangeLog/3.0
> The read-only block drivers "bochs", "cloop" and "dmg" as well as "rbd" and "vvfat" in certain read-only configurations will no longer enable read-only mode automatically. It will be necessary to specify "read-only=on" explicitly on the command line and in QMP commands for the setup to keep working; the default "read-only=off" setting will result in an error.
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
=> avoid qemu warning and error when useing vvfat volume

docs/design.md, docs/pmctl.md, docs/resource.md, docs/virtual_bmc.md
This PR adds v2 design documents that cover the following topics.
- Remove the dependency on `rkt`
- Running Placemat inside a Kubernetes Pod
- Virtual BMC supports Redfish API
=> Placemat v2 Design Documents

v2/pkg/dcnet/mtu.go
The new implementation first tries to detect the right device
used for communication to the Internet.  If there is no such
device, it returns the minimum MTU of the physical links.
=> dcnet: detect MTU by "ip route get"

v2/pkg/placemat/cluster.go, v2/pkg/virtualbmc/bmc_server.go, v2/pkg/virtualbmc/bmc_server_test.go, v2/pkg/virtualbmc/gencert.go, v2/pkg/vm/bmc.go, v2/pkg/vm/runtime.go
This PR fixes the BMC server error caused by the TLS certificates conflict. BMC servers write certificates on the same directory and that leads to the server startup failure. Placemat no longer generates certificate files with this PR.
=> Fix BMC server startup failure

bin/env, v2/e2e/placemat_test.go, v2/pkg/placemat/server.go, v2/pkg/virtualbmc/bmc_server.go
This PR fixes the internal server error that aborts node list command when vm's powers status cannot be confirmed.  `pmctl2 node list` lists VM list without showing internal server error.  `pmctl2 node show` shows `power_Status: Unknown` as follows.
```
$ pmctl2 node show boot-0 | jq .
{
"name": "boot-0",
"taps": {
"r0-node1": "pm_tap04562b3f",
"r0-node2": "pm_tap61b6b82f"
},
"volumes": [
"root",
"seed",
"sabakan"
],
"cpu": 8,
"memory": "4G",
"uefi": false,
"tpm": false,
"smbios": {
"manufacturer": "",
"product": "",
"serial": "fb8f2417d0b4db30050719c31ce02a2e8141bbd8"
},
"power_status": "Unknown",
"socket_path": "/tmp/boot-0.socket"
}
```
=> Fix Internal Server Error when vm's power status cannot be confirmed

v2/pkg/vm/qemu.go, v2/pkg/vm/qemu_test.go, v2/pkg/vm/volume.go, v2/pkg/vm/volume_test.go
QEMU raises the permission error "Cannot get 'write' permission without 'resize': Image size is not a multiple of request alignment",
if a target image is not 4k aligned, and WRITE permission is granted but RESIZE is not.
To work around the issue, we change the localds image fomat from raw to qcow2 not to generate an unaligned seed image.
See
https://github.com/qemu/qemu/commit/9c60a5d1978e6dcf85c0e01b50e6f7f54ca09104
https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1921665
=> Fix the permission error

docs/resource.md, v2/e2e/cluster.yml, v2/pkg/types/cluster.go, v2/pkg/types/cluster_test.go, v2/pkg/vm/node.go, v2/pkg/vm/qemu.go, v2/pkg/vm/qemu_test.go, v2/pkg/vm/tap.go, v2/pkg/vm/tap_test.go
=> Support Multiqueue virtio-net

docs/resource.md, examples/cluster.example.yml, v2/pkg/placemat/cluster.go, v2/pkg/types/cluster.go, v2/pkg/vm/node.go, v2/pkg/vm/qemu_test.go, v2/pkg/vm/volume.go, v2/pkg/vm/volume_test.go
This PR implements multiple device backends supports for placemat VMs.
Users can use multiple device backends by specifying DeviceClass as follows.
```
kind: DeviceClass
name: ssd
path: /var/scratch/ssd
---
kind: Node
volumes:
- cache: none
format: raw
kind: raw
name: data1
size: 50G
deviceClass: ssd
```
issue: cybozu/csa#62
Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>
Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>
=> Support multiple device backends for placemat VMs

docs/resource.md, v2/pkg/types/cluster.go, v2/pkg/types/cluster_test.go, v2/pkg/vm/node.go, v2/pkg/vm/qemu.go, v2/pkg/vm/qemu_test.go
part of https://github.com/cybozu-go/neco/issues/1977
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>
=> add simple NUMA support

examples/README.md
part of https://github.com/cybozu-go/neco/issues/2082.
=> Fix URL of Flatcar's Docs

v2/version.go
I forgot to update version.go in https://github.com/cybozu-go/placemat/pull/184 PR, so only version.go is updated.
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>
=> Update version.go to 2.4.2
